//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char snake_sn [] = {
0x00, 0x03, 0x00, 0x02, 

};
